/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_manufacturer_name_string       16
#define gattdb_system_id                      18
#define gattdb_led                            21
#define gattdb_temperature_measurement        24
#define gattdb_temperature_type               27
#define gattdb_intermediate_temperature       29
#define gattdb_measurement_interval           32
#define gattdb_valid_range                    34
#define gattdb_ota_control                    37


#endif // __GATT_DB_H
